// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FLOATMORSEL_IMPRESARIOSERIALIZATION_H_
#define FLATBUFFERS_GENERATED_FLOATMORSEL_IMPRESARIOSERIALIZATION_H_

#include "flatbuffers/flatbuffers.h"

namespace ImpresarioSerialization {

struct FloatMorsel;
struct FloatMorselBuilder;

struct FloatMorsel FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef FloatMorselBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FIELD = 4,
    VT_VALUE = 6
  };
  uint64_t field() const {
    return GetField<uint64_t>(VT_FIELD, 0);
  }
  float value() const {
    return GetField<float>(VT_VALUE, 0.0f);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_FIELD) &&
           VerifyField<float>(verifier, VT_VALUE) &&
           verifier.EndTable();
  }
};

struct FloatMorselBuilder {
  typedef FloatMorsel Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_field(uint64_t field) {
    fbb_.AddElement<uint64_t>(FloatMorsel::VT_FIELD, field, 0);
  }
  void add_value(float value) {
    fbb_.AddElement<float>(FloatMorsel::VT_VALUE, value, 0.0f);
  }
  explicit FloatMorselBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<FloatMorsel> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<FloatMorsel>(end);
    return o;
  }
};

inline flatbuffers::Offset<FloatMorsel> CreateFloatMorsel(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t field = 0,
    float value = 0.0f) {
  FloatMorselBuilder builder_(_fbb);
  builder_.add_field(field);
  builder_.add_value(value);
  return builder_.Finish();
}

inline const ImpresarioSerialization::FloatMorsel *GetFloatMorsel(const void *buf) {
  return flatbuffers::GetRoot<ImpresarioSerialization::FloatMorsel>(buf);
}

inline const ImpresarioSerialization::FloatMorsel *GetSizePrefixedFloatMorsel(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<ImpresarioSerialization::FloatMorsel>(buf);
}

inline bool VerifyFloatMorselBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<ImpresarioSerialization::FloatMorsel>(nullptr);
}

inline bool VerifySizePrefixedFloatMorselBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<ImpresarioSerialization::FloatMorsel>(nullptr);
}

inline void FinishFloatMorselBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<ImpresarioSerialization::FloatMorsel> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedFloatMorselBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<ImpresarioSerialization::FloatMorsel> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace ImpresarioSerialization

#endif  // FLATBUFFERS_GENERATED_FLOATMORSEL_IMPRESARIOSERIALIZATION_H_
