// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FREQUENCYBAND_IMPRESARIOSERIALIZATION_H_
#define FLATBUFFERS_GENERATED_FREQUENCYBAND_IMPRESARIOSERIALIZATION_H_

#include "flatbuffers/flatbuffers.h"

namespace ImpresarioSerialization {

enum class FrequencyBand : int8_t {
  all = 0,
  subBass = 1,
  bass = 2,
  lowMidrange = 3,
  midrange = 4,
  upperMidrange = 5,
  presence = 6,
  brilliance = 7,
  MIN = all,
  MAX = brilliance
};

inline const FrequencyBand (&EnumValuesFrequencyBand())[8] {
  static const FrequencyBand values[] = {
    FrequencyBand::all,
    FrequencyBand::subBass,
    FrequencyBand::bass,
    FrequencyBand::lowMidrange,
    FrequencyBand::midrange,
    FrequencyBand::upperMidrange,
    FrequencyBand::presence,
    FrequencyBand::brilliance
  };
  return values;
}

inline const char * const *EnumNamesFrequencyBand() {
  static const char * const names[9] = {
    "all",
    "subBass",
    "bass",
    "lowMidrange",
    "midrange",
    "upperMidrange",
    "presence",
    "brilliance",
    nullptr
  };
  return names;
}

inline const char *EnumNameFrequencyBand(FrequencyBand e) {
  if (flatbuffers::IsOutRange(e, FrequencyBand::all, FrequencyBand::brilliance)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesFrequencyBand()[index];
}

}  // namespace ImpresarioSerialization

#endif  // FLATBUFFERS_GENERATED_FREQUENCYBAND_IMPRESARIOSERIALIZATION_H_
