// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ONSETPROCESSORPARAMETERS_IMPRESARIOSERIALIZATION_H_
#define FLATBUFFERS_GENERATED_ONSETPROCESSORPARAMETERS_IMPRESARIOSERIALIZATION_H_

#include "flatbuffers/flatbuffers.h"

#include "FrequencyBand_generated.h"
#include "OnsetMethod_generated.h"

namespace ImpresarioSerialization {

struct OnsetProcessorParameters;
struct OnsetProcessorParametersBuilder;

struct OnsetProcessorParameters FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef OnsetProcessorParametersBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_METHOD = 4,
    VT_THRESHOLD = 6,
    VT_PEAKPICKINGWINDOWSIZE = 8,
    VT_PEAKPICKINGWINDOWTAILMULTIPLIER = 10
  };
  ImpresarioSerialization::OnsetMethod method() const {
    return static_cast<ImpresarioSerialization::OnsetMethod>(GetField<int8_t>(VT_METHOD, 0));
  }
  float threshold() const {
    return GetField<float>(VT_THRESHOLD, 0.0f);
  }
  uint8_t peakPickingWindowSize() const {
    return GetField<uint8_t>(VT_PEAKPICKINGWINDOWSIZE, 0);
  }
  uint8_t peakPickingWindowTailMultiplier() const {
    return GetField<uint8_t>(VT_PEAKPICKINGWINDOWTAILMULTIPLIER, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_METHOD) &&
           VerifyField<float>(verifier, VT_THRESHOLD) &&
           VerifyField<uint8_t>(verifier, VT_PEAKPICKINGWINDOWSIZE) &&
           VerifyField<uint8_t>(verifier, VT_PEAKPICKINGWINDOWTAILMULTIPLIER) &&
           verifier.EndTable();
  }
};

struct OnsetProcessorParametersBuilder {
  typedef OnsetProcessorParameters Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_method(ImpresarioSerialization::OnsetMethod method) {
    fbb_.AddElement<int8_t>(OnsetProcessorParameters::VT_METHOD, static_cast<int8_t>(method), 0);
  }
  void add_threshold(float threshold) {
    fbb_.AddElement<float>(OnsetProcessorParameters::VT_THRESHOLD, threshold, 0.0f);
  }
  void add_peakPickingWindowSize(uint8_t peakPickingWindowSize) {
    fbb_.AddElement<uint8_t>(OnsetProcessorParameters::VT_PEAKPICKINGWINDOWSIZE, peakPickingWindowSize, 0);
  }
  void add_peakPickingWindowTailMultiplier(uint8_t peakPickingWindowTailMultiplier) {
    fbb_.AddElement<uint8_t>(OnsetProcessorParameters::VT_PEAKPICKINGWINDOWTAILMULTIPLIER, peakPickingWindowTailMultiplier, 0);
  }
  explicit OnsetProcessorParametersBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<OnsetProcessorParameters> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<OnsetProcessorParameters>(end);
    return o;
  }
};

inline flatbuffers::Offset<OnsetProcessorParameters> CreateOnsetProcessorParameters(
    flatbuffers::FlatBufferBuilder &_fbb,
    ImpresarioSerialization::OnsetMethod method = ImpresarioSerialization::OnsetMethod::specflux,
    float threshold = 0.0f,
    uint8_t peakPickingWindowSize = 0,
    uint8_t peakPickingWindowTailMultiplier = 0) {
  OnsetProcessorParametersBuilder builder_(_fbb);
  builder_.add_threshold(threshold);
  builder_.add_peakPickingWindowTailMultiplier(peakPickingWindowTailMultiplier);
  builder_.add_peakPickingWindowSize(peakPickingWindowSize);
  builder_.add_method(method);
  return builder_.Finish();
}

inline const ImpresarioSerialization::OnsetProcessorParameters *GetOnsetProcessorParameters(const void *buf) {
  return flatbuffers::GetRoot<ImpresarioSerialization::OnsetProcessorParameters>(buf);
}

inline const ImpresarioSerialization::OnsetProcessorParameters *GetSizePrefixedOnsetProcessorParameters(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<ImpresarioSerialization::OnsetProcessorParameters>(buf);
}

inline bool VerifyOnsetProcessorParametersBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<ImpresarioSerialization::OnsetProcessorParameters>(nullptr);
}

inline bool VerifySizePrefixedOnsetProcessorParametersBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<ImpresarioSerialization::OnsetProcessorParameters>(nullptr);
}

inline void FinishOnsetProcessorParametersBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<ImpresarioSerialization::OnsetProcessorParameters> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedOnsetProcessorParametersBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<ImpresarioSerialization::OnsetProcessorParameters> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace ImpresarioSerialization

#endif  // FLATBUFFERS_GENERATED_ONSETPROCESSORPARAMETERS_IMPRESARIOSERIALIZATION_H_
