// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ONSETMETHOD_IMPRESARIOSERIALIZATION_H_
#define FLATBUFFERS_GENERATED_ONSETMETHOD_IMPRESARIOSERIALIZATION_H_

#include "flatbuffers/flatbuffers.h"

namespace ImpresarioSerialization {

enum class OnsetMethod : int8_t {
  specflux = 0,
  MIN = specflux,
  MAX = specflux
};

inline const OnsetMethod (&EnumValuesOnsetMethod())[1] {
  static const OnsetMethod values[] = {
    OnsetMethod::specflux
  };
  return values;
}

inline const char * const *EnumNamesOnsetMethod() {
  static const char * const names[2] = {
    "specflux",
    nullptr
  };
  return names;
}

inline const char *EnumNameOnsetMethod(OnsetMethod e) {
  if (flatbuffers::IsOutRange(e, OnsetMethod::specflux, OnsetMethod::specflux)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesOnsetMethod()[index];
}

}  // namespace ImpresarioSerialization

#endif  // FLATBUFFERS_GENERATED_ONSETMETHOD_IMPRESARIOSERIALIZATION_H_
