# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ImpresarioSerialization

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Onset(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Onset()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOnset(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Onset
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Onset
    def OriginTimestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Onset
    def FrequencyBand(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # Onset
    def Method(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # Onset
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Onset
    def Confidence(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def Start(builder): builder.StartObject(5)
def OnsetStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddOriginTimestamp(builder, originTimestamp): builder.PrependUint64Slot(0, originTimestamp, 0)
def OnsetAddOriginTimestamp(builder, originTimestamp):
    """This method is deprecated. Please switch to AddOriginTimestamp."""
    return AddOriginTimestamp(builder, originTimestamp)
def AddFrequencyBand(builder, frequencyBand): builder.PrependInt8Slot(1, frequencyBand, 0)
def OnsetAddFrequencyBand(builder, frequencyBand):
    """This method is deprecated. Please switch to AddFrequencyBand."""
    return AddFrequencyBand(builder, frequencyBand)
def AddMethod(builder, method): builder.PrependInt8Slot(2, method, 0)
def OnsetAddMethod(builder, method):
    """This method is deprecated. Please switch to AddMethod."""
    return AddMethod(builder, method)
def AddTimestamp(builder, timestamp): builder.PrependUint64Slot(3, timestamp, 0)
def OnsetAddTimestamp(builder, timestamp):
    """This method is deprecated. Please switch to AddTimestamp."""
    return AddTimestamp(builder, timestamp)
def AddConfidence(builder, confidence): builder.PrependFloat32Slot(4, confidence, 0.0)
def OnsetAddConfidence(builder, confidence):
    """This method is deprecated. Please switch to AddConfidence."""
    return AddConfidence(builder, confidence)
def End(builder): return builder.EndObject()
def OnsetEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)